### ISSUE TITLE
AlloySmelter.addRecipe cause a crash the game with last version of ender IO (1.12.2-5.3.68)

### ISSUE THREAD

**Issue by NeutronSelector** [Shadows-of-Fire/EnderTweaker#21]
After updating Ender IO in last version, this line in my script throw an exception on game launch (in phase 4 of 7 of forge loader) 

Script line causing this issue :
`mods.enderio.AlloySmelter.addRecipe(<minecraft:iron_nugget> * 9, [<exnihilocreatio:item_ore_iron:1>], 2000);`

This line work perfectly before updating Ender IO in version 1.12.2-5.3.68

Crash report : 
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EnderTweaker (endertweaker)
Caused by: java.lang.NoSuchMethodError: crazypants.enderio.base.recipe.alloysmelter.AlloyRecipeManager.addRecipe(Lcrazypants/enderio/base/recipe/Recipe;)V
    at shadows.endertweaker.AlloySmelter.lambda$addRecipe$0(AlloySmelter.java:37)
    at shadows.endertweaker.AlloySmelter$$Lambda$4146/2140640543.run(Unknown Source)
    at shadows.endertweaker.EnderTweaker.loadComplete(EnderTweaker.java:30)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:757)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Thank's for your help.

**Comment by Krutoy242** [comment]
Experience same. Need fix.

**Comment by NeutronSelector** [comment]
Hello, 
#22 this pull request fix the crash but the new recipes doesn't work in AlloySmelte.

I have no errors or crashes while loading the modpack and the world. The new recipes are displayed in JEI. But when I try the new recipe in AlloySmelter, nothing happens. And after putting the input item once in one of the top solts, I can't put it back. As if the recipe was no longer known.

My very simple test script:
mods.enderio.AlloySmelter.addRecipe(<minecraft:iron_nugget> * 9, [<exnihilocreatio:item_ore_iron:1>], 4000);

Thank's for your help.
